### ___________________________________________________________________________________
@HOST=http://0.0.0.0:5002
### ___________________________________________________________________________________




### ===================================== U S E R =====================================
POST {{HOST}}/user HTTP/1.1
Content-Type: application/json

{
  "name": "Test",
  "email": "joao@email.com",
  "password": "test123"
}

###

POST {{HOST}}/authenticate HTTP/1.1
Content-Type: application/json

{
  "email": "guilherme@email.com",
  "password": "test"
}

### ===================================== N E W S =====================================

POST {{HOST}}/news/ HTTP/1.1
Content-Type: application/json

{
  "title": "Novo Iphone X",
  "type": "Pet",
  "image": "www.google.com/image",
  "content": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sint vel illo, ipsum illum perspiciatis corporis? Repudiandae, expedita tenetur velit, eveniet repellendus et a ipsum officiis fugiat hic, nisi doloribus animi. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sint vel illo, ipsum illum perspiciatis corporis? Repudiandae, expedita tenetur velit, eveniet repellendus et a ipsum officiis fugiat hic, nisi doloribus animi.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sint vel illo, ipsum illum perspiciatis corporis? Repudiandae, expedita tenetur velit, eveniet repellendus et a ipsum officiis fugiat hic, nisi doloribus animi."
}

###

PUT {{HOST}}/news/7f3a0fc4-6aaf-43c3-900d-73af8751561b HTTP/1.1
Content-Type: application/json

{
  "title": "Teste",
  "type": "science",
  "image": "www.test.com",
  "content": "data content"
}

###

DELETE {{HOST}}/news/7f3a0fc4-6aaf-43c3-900d-73af8751561b HTTP/1.1

###

GET {{HOST}}/news/ HTTP/1.1

###
GET {{HOST}}/news/cfee252b-dcf0-4c46-a201-44605dfdb2ca HTTP/1.1
